name: siren-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - torch_geometric
    - numpy
    - pandas
    - scikit-learn
    - tqdm
    - scipy
    - wandb
